In [1]:
import numpy as np
import tensorflow as tf
import pandas as pd

In [2]:
ratings = pd.read_csv('datasets/ratings.csv')
movies = pd.read_csv('datasets/movies.csv', index_col='movieId')

In [3]:
loaded_data = np.load('recommender_weights.npz')

Y_pivot = ratings.pivot_table(index='movieId', columns='userId', values='rating').fillna(0)
Y = Y_pivot.to_numpy()
X = tf.Variable(loaded_data['X'], dtype=tf.float32)
W = tf.Variable(loaded_data['W'], dtype=tf.float32)
b = tf.Variable(loaded_data['b'], dtype=tf.float32)
movie_mean = tf.constant(loaded_data['movie_means'], dtype=tf.float32)

pred_Y = X @ tf.transpose(W) + b
pred_Y = pred_Y + movie_mean

In [4]:
userId = 123
userIdIdx = userId - 1
my_ratings = Y[:, userIdIdx]
rated_indices = np.where(my_ratings > 0)[0]
rated_movie_ids = Y_pivot.index[rated_indices]
print(f"Movies rated by User {userId}:")
display(movies.loc[rated_movie_ids])

Movies rated by User 123:

,title,genres
movieId,,
47,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
260,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi
293,Léon: The Professional (a.k.a. The Professiona...,Action|Crime|Drama|Thriller
296,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller
318,"Shawshank Redemption, The (1994)",Crime|Drama
593,"Silence of the Lambs, The (1991)",Crime|Horror|Thriller
1196,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Sci-Fi
2329,American History X (1998),Crime|Drama
2571,"Matrix, The (1999)",Action|Sci-Fi|Thriller
2858,American Beauty (1999),Drama|Romance
2959,Fight Club (1999),Action|Crime|Drama|Thriller
4226,Memento (2000),Mystery|Thriller
4776,Training Day (2001),Crime|Drama|Thriller
4886,"Monsters, Inc. (2001)",Adventure|Animation|Children|Comedy|Fantasy
4993,"Lord of the Rings: The Fellowship of the Ring,...",Adventure|Fantasy
5952,"Lord of the Rings: The Two Towers, The (2002)",Adventure|Fantasy
6016,City of God (Cidade de Deus) (2002),Action|Adventure|Crime|Drama|Thriller
7153,"Lord of the Rings: The Return of the King, The...",Action|Adventure|Drama|Fantasy
44199,Inside Man (2006),Crime|Drama|Thriller
48780,"Prestige, The (2006)",Drama|Mystery|Sci-Fi|Thriller
51540,Zodiac (2007),Crime|Drama|Thriller
54286,"Bourne Ultimatum, The (2007)",Action|Crime|Thriller
55765,American Gangster (2007),Crime|Drama|Thriller
58803,21 (2008),Crime|Drama|Romance|Thriller
59315,Iron Man (2008),Action|Adventure|Sci-Fi
60684,Watchmen (2009),Action|Drama|Mystery|Sci-Fi|Thriller|IMAX
64969,Yes Man (2008),Comedy
68157,Inglourious Basterds (2009),Action|Drama|War
68554,Angels & Demons (2009),Crime|Drama|Mystery|Thriller
69306,"Taking of Pelham 1 2 3, The (2009)",Crime|Drama|Thriller
76093,How to Train Your Dragon (2010),Adventure|Animation|Children|Fantasy|IMAX
79132,Inception (2010),Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX
80463,"Social Network, The (2010)",Drama
81782,Unstoppable (2010),Action|Drama|Thriller
84152,Limitless (2011),Sci-Fi|Thriller
85414,Source Code (2011),Action|Drama|Mystery|Sci-Fi|Thriller
87232,X-Men: First Class (2011),Action|Adventure|Sci-Fi|Thriller|War
89745,"Avengers, The (2012)",Action|Adventure|Sci-Fi|IMAX
91500,The Hunger Games (2012),Action|Adventure|Drama|Sci-Fi|Thriller
91542,Sherlock Holmes: A Game of Shadows (2011),Action|Adventure|Comedy|Crime|Mystery|Thriller
96829,"Hunt, The (Jagten) (2012)",Drama
97923,Flight (2012),Drama
99114,Django Unchained (2012),Action|Drama|Western
104879,Prisoners (2013),Drama|Mystery|Thriller
104913,Rush (2013),Action|Drama
106920,Her (2013),Drama|Romance|Sci-Fi
109487,Interstellar (2014),Sci-Fi|IMAX
111759,Edge of Tomorrow (2014),Action|Sci-Fi|IMAX
112171,"Equalizer, The (2014)",Action|Crime|Thriller
112552,Whiplash (2014),Drama
112556,Gone Girl (2014),Drama|Thriller
112852,Guardians of the Galaxy (2014),Action|Adventure|Sci-Fi
115569,Nightcrawler (2014),Crime|Drama|Thriller
115617,Big Hero 6 (2014),Action|Animation|Comedy
116797,The Imitation Game (2014),Drama|Thriller|War
143458,The Great Hypnotist (2014),Drama|Mystery|Thriller

In [5]:
my_predictions = pred_Y[:, userIdIdx]

my_predictions = tf.where(
    my_ratings > 0,
    tf.constant(-1.0),
    my_predictions
)
top_10_indices = np.argsort(my_predictions)[::-1][:10]
top_10_movie_ids = Y_pivot.index[top_10_indices]

print(f"\nUser {userId} may like the following movies:")
display(movies.loc[top_10_movie_ids])

User 123 may like the following movies:

,title,genres
movieId,,
926,All About Eve (1950),Drama
2186,Strangers on a Train (1951),Crime|Drama|Film-Noir|Thriller
1283,High Noon (1952),Drama|Western
6188,Old School (2003),Comedy
3910,Dancer in the Dark (2000),Drama|Musical
4366,Atlantis: The Lost Empire (2001),Adventure|Animation|Children|Fantasy
5785,Jackass: The Movie (2002),Action|Comedy|Documentary
1945,On the Waterfront (1954),Crime|Drama
1680,Sliding Doors (1998),Drama|Romance
218,Boys on the Side (1995),Comedy|Drama